appname: config_200ms_2c_64
device: cuda:1
datatype: const_time
dataset:
    zero_center: 0
    keep_polarity: 1
    resolution: 64
show_feature_maps: 0 # create images of ofms (ANN)
show_raster_plots: 0 # create images spike ofms + raster plots
ann_to_snn:
    fire_last_layer: 0
    merge_BN: 0
    compensate_for_mean: 0
    compute_th: 0
    percentile: 99.7
    convert: 0
    simulate: 1
    simulation_params: 
        delayed_spikes: 0 # T/F
        delayed_cyclic: 0 # T/F
        delayed_piped: 0
        delay_type: type3 # type2, type3
        gate_time: -1
        fire_time: 100
        delayed_hybrid: False # T/F
        num_delayed_layers: 1
        tWindow: 40 # in ms (for poisson spikes)
        tDuration: 1450 # in ms (total duration of dvs events)
        reset_time: 100 # in ms (break down the total duration)
        input_type: aedat # poisson, aedat, aedat_raw
        record_spikes: 0
        record_poisson_spikes: 0
        save_activation: 0
        extra_time: 0
        Zee: 1
        optimize_mem: 1 # 0,1,2 fast--->slow
        num_frame_repeats: 1
        #num_frame_repeats: -1 # a neg val means use const tWindow and repeat as many times
        interleave: 0
        measure_sparsity: 0
        combine_frames: 0
        combine_factor: 24
        measure_ops: 1
training:
    eval: 0
    learn: 0
    convert: False
    resume: 1
    batch_size: 64
    num_epochs: 150
    lr: 0.00005 # 0.0001 # 0.0005 # 0.001
    aedat_path: 
        in:    /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constTime_200ms_all
        train: /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constTime_200ms_all/train.txt
        test:  /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constTime_200ms_all/test.txt
    path:
        const_event:
            in:    /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constTime_200ms_all
            train: /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constTime_200ms_all/train.txt
            test:  /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constTime_200ms_all/test.txt
