appname: config_11k_2c_64_deep
device: cuda:0
simulation:
    Ts: 1
    tSample: 1450
datatype: const_event
dataset:
    zero_center: 0
    keep_polarity: 1
    resolution: 64
show_feature_maps: 0 # create images of ofms (ANN)
show_raster_plots: 0 # create images spike ofms + raster plots
show_wt_l2_norm: 1
ann_to_snn:
    fire_last_layer: 0
    merge_BN: 0
    compensate_for_mean: 0
    compute_th: 0
    percentile: 99.7
    convert: 0
    simulate: 0
    simulation_params: 
        delayed_spikes: 1 # T/F
        delayed_cyclic: 1 # T/F
        delayed_hybrid: False # T/F
        num_delayed_layers: 1
        tWindow: 100 # in ms (for poisson spikes)
        tDuration: 1450 # in ms (total duration of dvs events)
        reset_time: 100 # in ms (break down the total duration)
        input_type: aedat # poisson, aedat, aedat_raw
        record_spikes: 0
        record_poisson_spikes: 0
        save_activation: 0
        extra_time: 0
        Zee: 1
        optimize_mem: 1 # 0,1,2 fast--->slow
        num_frame_repeats: 1
        #num_frame_repeats: -1 # a neg val means use const tWindow and repeat as many times
        interleave: 0
        measure_sparsity: 0
training:
    eval: 0
    learn: 0
    convert: False
    resume: 1
    batch_size: 128
    num_epochs: 200
    lr: 0.0001 #0.001 #0.00007 #0.0001 # 0.0005 # 0.001 
    train: {start: 0, stop: 1450, tInt: 50}    # start and stop times in ms
    test: {start: 0, stop: 1450, tInt: 100}    # start and stop times in ms
    aedat_path: 
        in:    /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constEvt_11k_all
        train: /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constEvt_11k_all/train.txt
        test:  /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constEvt_11k_all/test.txt
    path:
        const_event:
            in:    /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constEvt_11k_all
            train: /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constEvt_11k_all/train.txt
            test:  /i3c/hpcl/sms821/Research/SpikSim/slayer_scratch/slayerPytorch/example/12_datasets/2x64x64/constEvt_11k_all/test.txt
        const_time:
            in:      
            train:   
            test:    
